### ISSUE TITLE
Document Npm2 compared to Npm3 behaviour

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#103]
Add to README.md explanation about different ways to use with Npm2 compared to Npm3 and also PR Angular 2.0 docs to explain the same thing

**Comment by barbatus** [comment]
As I can see, there is only one difference in behavior  between NPM2 and NPM3 relatively to this package: the former installs peer dependencies first time (but each next time it shows warnings), the latter doesn't install anything at all showing only warnings.
I just changed the README to recommend adding all dependencies in the package.json at the start, so I think this issue is bot relevant any more.
