### ISSUE TITLE
Add comments to tsconfig file on Angular 2.0 requirements, with links

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular2-meteor#108]
and add comments on everything in tsconfig..

**Comment by dotansimha** [comment]
JSON files does not allow comments inside them, so I think that the best solution is to provide an example for `tsconfig.json` file and explain each property in the tutorial...

**Comment by barbatus** [comment]
TypeScript package goes with a default configuration (will be described on the typescript package's page once it's matured enough) targeted for Meteor 1.3. That config should be enough for most cases w/o additional options.
As to Meteor 1.2's Angular2-Meteor, TS compiler there has also some viable default configuration that should be enough in most cases as well.
Otherwise, all information are provided here https://github.com/Microsoft/TypeScript/wiki/Compiler-Options.
