### ISSUE TITLE
Meteor packages: Iron Router, Collection2, Accounts

### ISSUE THREAD

**Issue by deltaag** [Urigo/angular2-meteor#137]
I am new to Meteor and Angular world, and this is a question rather than an issue.
Is it possible to use meteor packages like Iron Router, Collections2, Accounts, and so on if I use angular2 and Type Script in a project?

**Comment by dotansimha** [comment]
Yeah sure, I guess that you use Meteor 1.2, so all you need to to is add the package you want, for example:
````
meteor add accounts-base accounts-password
````

And then just use it as a global like a regular work with JS. Same with Collections2.
Not sure about Iron Router, because I think that he depends on packages like `Blaze` and `templating` which conflicts with the Angular html compiler. 

For more information and actual examples, please follow the Angular 2 tutorial on http://angular-meteor.com , it covers that usage with Collections and Accounts.

**Comment by deltaag** [comment]
Thanks @dotansimha 
I found out dependency packages list (and also dependants) is available in atmospherejs.com for each package. I believe that list can help to figure out if a package will work with angular2 or not.
