### ISSUE TITLE
Doubts to install Angular2 and Meteor

### ISSUE THREAD

**Issue by celsomtrindade** [Urigo/angular2-meteor#182]
First of all I'm new to Angular2 and, specially, with Meteor (first time I'm trying). I'm having trouble installing it with Angular2 when it comes down to the Angular2 part. I could install the meteor, remove the packages accordingly but when I need to run:

    meteor add urigo:angular2-meteor

It has a progress bar on the prompt but after it finishes, there is no file in the folder and no errors in the prompt. I tried to check the version of meteor and used this command: `meteor -v`, some how it started the server and the folder appear, is there any problem with it?

Also, after that, when I tried to access the page, it gives me these errors on the prompt: 

> Cannot find module 'angular2/core'
> Cannot find module 'angular2/platform/browser'
> Cannot find module 'angular2/core'

But no errors on the console.

I also noticed there is no JS file on the folders but when I was using pure Angular2, there were an auto compiler to convert my `.ts` files to `.js`.

Also, the index.html has no reference to externals files, such as the angular2 library, etc.. Do I need to add it manually? Or just stick to the tutorial and use a plain and simple index with just the body tag?

The tutorial is very explained, but I'm felling it a bit technical for a begginer like me.

**Comment by rvetere** [comment]
Hi @celsomtrindade - i can feel your struggle.. ;) Now, first thing, you should use meteor1.3 now, i guess you're already on it as it is released now since a good week. So, check first:

`meteor --version`

in your project directory and if you're not on the latest 1.3 release, run:

`meteor update --release 1.3`

Then, most important change with release 1.3 is the native npm package support - so the packages of angular2-meteor and more are moved to npm instead of meteor atmosphere like in old days. Instead of adding the package with `meteor add` like you did, do it with npm now:

`npm install --save angular2-meteor`
`npm install --save angular2-meteor-auto-bootstrap`

Also, add the awesome bootstrap package which adds all the meteor magic to your app just by using this bootstrap instead of the original angular2 one.

You can check your .meteor/package file if there is an entry of "angular2-meteor", if so, remove it by running:

`meteor remove angular2-meteor`

so he will remove everything dependent on it too and change your files accordingly in .meteor dir ;)

Now, the basic package "angular2-meteor" should bring all the core packages of angular as peer-dependencies.. if not, copy-paste manually those entries into your package.json under "dependencies":

`"angular2": "2.0.0-beta.12"`

I'm not sure about the polyfills.. in my current project i still imported all of the following too:

`"es6-promise": "^3.1.2",
`"es6-shim": "^0.35.0",`
`"reflect-metadata": "^0.1.3",`
`"rxjs": "^5.0.0-beta.4",`
`"zone.js": "^0.6.8"`

At this point.. i guess you should be able to follow along the tutorial again ;)

**Comment by Urigo** [comment]
@celsomtrindade I've seen you issue and waited very patiently so I will be able to answer the following answer:
We have just deployed a new version of the tutorial which is updated to Meteor 1.3 and the new modules system and npm!
Please check the updated version of the tutorial and let me know about more doubts and I hope I can answer them!
Good luck and welcome aboard!
