### ISSUE TITLE
unlink angular2-runtime

### ISSUE THREAD

**Issue by hlehmann** [Urigo/angular2-meteor#187]
Hi,

I know that angular2-runtime could help starting a project with angular2 but it also make it redundant with node_modules dependencies.

For example I use angular2-moment which installs angular2. I also want to be able to chose which version I want to use

Is it possible to remove angular2-runtime from angular2-compilers dependencies, and just have both of them available ?

**Comment by barbatus** [comment]
Don't know what you meant "angular2-moment installs angular2". angular2-moment doesn't have any peer dependencies.
angular2-runtime adds bunch of stuff required by Angular2 like reflect-metadata, angular2-polyfills.js etc, otherwise you'll need to add everything either using `<script>` or direct by importing them in ts-files. Second, version of Angular2 that is peer-required by Angular2-Meteor NPM has been tested and guaranteed to work with Meteor. To sum up, the structure you can see now is not without purpose, and don't see big reasons to change it now: I'll be updating and testing every next Angular version for this repo gradually until release candidates.

**Comment by hlehmann** [comment]
angular2-moment currently have angular2 in its "dependencies" but I ask to move it to their peerDependencies. But still angular2-meteor-auto-bootstrap or ionic-framework have it.

Once angular2-moment will use peerDependencies, `npm i` (v3) will not install angular2. However `meteor npm i` (v2) will do so. It's clearly not urgent but in order to follow the meteor strategy to move dependencies to npm (except for compilers) it would be useful to let developers having the choice between atmosphere and npm.

```
# for those who wants a quick access to angular 
meteor add angular2-compilers
meteor add angular2-runtime

# for those who wants to use npm
meteor add angular2-compilers
npm i angular2 --save
...
```
Once again, it could wait, I override the barbatus:angular2-runtime for the moment.

**Comment by barbatus** [comment]
not sure if you saw my message about required polyfills. Vast majority people will certainly choose to install `angular2-runtime` instead of adding `reflect-metadata` in each file. Also, Angular2 is still in beta, which means it's still being changed (especially internally) and changes might affect Angular2-Meteor integration (as happened previously multiple times). So version you see in peerDependencies are tested to work well.

**Comment by hlehmann** [comment]
Yes for the beta period, things are moving fast and  it solve most of developers interrogations and that's good. I will reintroduction this in a more stable situation.

By the way thx for making angular2 available for meteor.

**Comment by barbatus** [comment]
@hlehmann I try to keep up and update to the latest versions asap. Recently I tested beta.11 and got this error https://github.com/angular/angular/issues/7680, for example. So, all for good. Closing this issue for now.

**Comment by Urigo** [comment]
@barbatus sorry but I think @hlehmann has a point.
Meteor 1.3 goal is to make it open for other to use resources from npm like they would in a regular node environment. (we are not fully there but we are getting close).
It also means sometimes losing the great power of Meteor that guarantees that everything works.

For now the solution is great but I'm re-opening the issue as I think a future solution would look something like having a weak dependency on `angular2-runtime` and having it as a recommended option for developers.
I also hope that the Angular team will find better ways of distributing the library.

**Comment by hlehmann** [comment]
I don't know to wait extend angular2-compilers needs angular2-runtime but we can imagine that like angular having an angular2 package with both angular2-compilers and angular2-runtime.

**Comment by u0m3** [comment]
Would it not be better (so, ok, not *better*, more like a *patch*) to mention in the docs that you have to add **angular2-rutime** besides **angular2-compilers** and leave them separate?
