### ISSUE TITLE
import meteor package?

### ISSUE THREAD

**Issue by ryuken** [Urigo/angular2-meteor#194]
I'm sorry if this is a dumb question.
I followed the tutorial perfectly.
I want to use a meteor package i.e. named 'gadicohen:headers'.
So you add this package by: meteor add gadicohen:headers

I can't figure out how to import this package in TypeScript.
How can I import the package?
I tried:
import headers from 'meteor/headers'
import headers from 'meteor/gadicohen:headers'
import headers from 'gadicohen:headers'
import headers from '{gadicohen:headers}'

none of them work for me. please help me

**Comment by Urigo** [comment]
@ryuken can you create an example project so we could PR it and show you there?

**Comment by DrDanRyan** [comment]
I think the package does not export anything, it just defines a global `headers` variable.  Can you check if `headers` is defined after the package has been added (no import necessary).

**Comment by ryuken** [comment]
it is defined in the browser, but I can't access it in TypeScript, is that because there are no typings for it or something?

**Comment by barbatus** [comment]
if you install old Atmosphere packages they are likely done in Meteor 1.2 style, which means you don't need to import anything from them like you did. You'll need to use global variables (like that `headers` variable) they export. If you get warnings that `headers` is not defined, it's because of missing definitions (typings) for this lib (`gadicohen:headers`). The only way to overcome it is to create own typings for this lib.

Also please ask questions not directly related to Angular2-Meteor using stackoverlow or forums.meteor.com.
