### ISSUE TITLE
angular2-compilers0.5.5-1 error

### ISSUE THREAD

**Issue by aelmottaki** [Urigo/angular2-meteor#210]
@barbatus  when i install angular2-compilers0.5.5_1  i get this error 
"Uncaught reflect-metadata shim is required when using class decorators"

**Comment by barbatus** [comment]
add barbatus:angular2-runtime and habituate looking at README briefly before submitting an issue.

**Comment by Devidian** [comment]
@barbatus just updated with `meteor update` and saw 

```
angular2-compilers            upgraded from 0.5.4 to 0.5.5_1
barbatus:angular2-runtime     **removed from your project**
barbatus:typescript           upgraded from 0.2.0 to 0.2.2
barbatus:typescript-compiler  upgraded from 0.5.0-beta.15 to 0.5.1
barbatus:typescript-runtime   upgraded from 0.1.0-beta.1 to 0.1.0
```

So i ran into the same issue. Good that i found this but why is it removed ?

**Comment by Urigo** [comment]
because we want `barbatus:angular2-runtime` to be optional.
It's a great package that makes it much easier to use Angular 2, but it also makes it different from the way regular Angular developers use Angular 2.0 (even though it's harder) and also it bounds you to a specific version of Angular.
So we made it optional so you could use it only if you want
