### ISSUE TITLE
Whitespace in templateUrl bug --> passing on error messages?

### ISSUE THREAD

**Issue by jahala** [Urigo/angular2-meteor#228]
I found this bug when I was trying to follow the tutorial, and had an actual whitespace at the end of a filename (app.html ) .. I'm on mac and created the file from sublime text, which resulted in this strange filename.. And this was driving me insane for two hours because it was not giving any errors when starting meteor, or when loading the page (in console).. It was just blank..

After I discovered the bug I also tested with adding a whitespace in the declaration and it produced the same error - with the same effects (displays nothing on page load, and no error in console).

```
@Component({
  selector: 'app',
  templateUrl: 'client/app.html ', <-- whitespace at the end after filename
})
```

Testing the same in plain angular2 gives the following error in console:
```
EXCEPTION: Error: Uncaught (in promise): Failed to load app.html%20
```

But for some reason meteor is not passing that error message on to the client when using angular-meteor? Isn't that information quite vital?

**Comment by barbatus** [comment]
Finally got to it. The reason is in that Meteor always returns main page content and 200 status on every unknown path, so for every path like `client/app.html ` Angular2 will get and parse main page as a template. It doesn't fail since it's a valid HTML.

The reason why Meteor always return 200 on every unknown path lies in the fact that Meteor's web server is supposed to be quite simple with only necessary "low level" features and not coming with any elaborated functionality like routing etc. In this way, responsibility to handle 404 and routing in general is handed over to the higher level custom components which might be as packages or as app itself. So if you used `flow-router` you could add 404 handling like here https://github.com/kadirahq/flow-router/issues/84.

But the true story is that you don't need URL paths now since we recommend to use inline templates like described here https://github.com/Urigo/angular2-meteor#static-resources.
