### ISSUE TITLE
fourseven:scss not building .scss files?

### ISSUE THREAD

**Issue by bjones6** [Urigo/angular2-meteor#244]
Seems like the angular2-compilers mucks with packages that affect the build process like fourseven:scss compiling .scss files or civilframe:angular-jade compiling .jade files.

Is there a work around for this or something I'm missing? Thanks.

**Comment by Hongbo-Miao** [comment]
Hi @bjones6 I am using [fourseven:scss](https://atmospherejs.com/fourseven/scss). It is working well in Meteor 1.3.

But I am not using civilframe:angular-jade.

**Comment by Hongbo-Miao** [comment]
I have same question.

Right now I am using [fourseven:scss](https://atmospherejs.com/fourseven/scss). And I use `styleUrls: ['aaa.scss']` in component, and have a separate **aaa.scss** file.
However, this is a wrong use actually. Because this makes **aaa.scss** global actually. Not inside the component.

I found this:
[How to include SCSS in components](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components). (and [How to add .jade support](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-add-.jade-support))
This uses **node-sass** and **sass-loader** from NPM.

But I don't know where to add `loaders: ['raw-loader', 'sass-loader']`.

**Comment by barbatus** [comment]
@bjones6 I just added `fourseven:scss` in an app with `angular2-compilers`, and then a `scss` file. `fourseven:scss` recognized and compiledit well. What problem do you have specifically? If it doesn't compile for you then I'll need a repo to reproduce.

**Comment by barbatus** [comment]
To track here https://github.com/Urigo/angular2-meteor/issues/270
