### ISSUE TITLE
Remove useless meteor-node-stubs

### ISSUE THREAD

**Issue by hlehmann** [Urigo/angular2-meteor#266]
Reflect-metadata have somewhere a
```
let nodeCrypto = isNode && require('crypto');
```
making the meteor compiler asking for `meteor-node-stubs` (that's why it's a dependency of angular2-meteor I suppose) but we do not need it. Is it a good way to avoid installing it ? Because it is quite big.

**Comment by hlehmann** [comment]
On production, my .js file is:
- 536Ko with meteor-node-stubs
- 359Ko by simply removing meteor-node-stubs

**Comment by hlehmann** [comment]
https://github.com/meteor/meteor/issues/7020

**Comment by barbatus** [comment]
There is no way to avoid installing `meteor-node-stubs` until Reflect-metadata has two separate versions for NodeJS and browsers.

**Comment by barbatus** [comment]
Another way is to not import `reflect-metadata` directly and use `barbatus:angular2-runtime` instead.

**Comment by hlehmann** [comment]
Hum, I really prefer importing angular through npm because it avoid some dependencies duplication and allow a beter control. But I will try to put just reflect-metadata in an meteor package

**Comment by hlehmann** [comment]
Following this idea I created a simple package with just the package.js file:
```
Package.describe({
    name: 'angular2-shim',
    summary: '',
    version: '0.0.1',
    git: '',
    documentation: ''
});

Npm.depends({
    'reflect-metadata': '0.1.3',
    'zone.js': '0.6.12'
});

Package.onUse(function (api) {
    api.use('modules');

    api.addFiles([
        '.npm/package/node_modules/reflect-metadata/Reflect.js',
        '.npm/package/node_modules/zone.js/dist/zone.js',
    ], 'client');
});
```
And  no more needs to make an `import "reflect-metadata"` or `import "zone.js"`, and no more needs for meteor-node-stubs.

Because it's a shim we could add this inside `angular2-compiler` or create a `angular2-shim`. What do you think ?

**Comment by Urigo** [comment]
@hlehmann thank you for that solution.

As said [here](https://github.com/meteor/meteor/issues/7020#issuecomment-218234060) and [here](https://github.com/Urigo/angular2-meteor/issues/266#issuecomment-218476522), `reflect-metadata` should have a better solution for distinguishing between Node and the browser otherwise not only Meteor but any other client bundling tool will require a shim for `crypto`. 
So I think having your package mentioned as a temporary solution for this issue is a good enough for now but I have 3 more thoughts:

1. Could you open a relevant issue on `reflect-metadata` and link to Ben's comment on the Meteor issue?
2. Could you PR the tutorial to mention you package?
3. Maybe change the name of your package to something more specific to the `reflect-metadata` problem?  `angular2-shim` is very general and I'm not sure it's covering it all (unless this is the plan and it that case, forget about it)

**Comment by barbatus** [comment]
@hlehmann It's said above that `barbatus:angular2-runtime` does the same.

**Comment by hlehmann** [comment]
Following this idea I created a simple package with just the package.js file:
```
Package.describe({
    name: 'angular2-shim',
    summary: '',
    version: '0.0.1',
    git: '',
    documentation: ''
});

Npm.depends({
    'reflect-metadata': '0.1.3',
    'zone.js': '0.6.12'
});

Package.onUse(function (api) {
    api.use('modules');

    api.addFiles([
        '.npm/package/node_modules/reflect-metadata/Reflect.js',
        '.npm/package/node_modules/zone.js/dist/zone.js',
    ], 'client');
});
```
And  no more needs to make an `import "reflect-metadata"` or `import "zone.js"`, and no more needs for meteor-node-stubs.

Because it's a shim we could add this inside `angular2-compiler` or create a `angular2-shim`. What do you think ?

**Comment by Urigo** [comment]
@barbatus does `barbatus:angular2-runtime` includes a shim for that as well?

**Comment by barbatus** [comment]
@Urigo shim for what?

**Comment by Urigo** [comment]
I see, so @hlehmann does using `barbatus:angular2-runtime` works for you?  can I close this?

**Comment by hlehmann** [comment]
My bad @barbatus I didn't really understand the role of `barbatus:angular2-runtime` (I thought angular2 was include in there but no) and it works well.

Also @barbatus removed `meteor-node-stubs` from dependencies so I'm closing this issue. Thanks.
