### ISSUE TITLE
Unable to import from typescript

### ISSUE THREAD

**Issue by trajano** [Urigo/angular2-meteor#275]
Just changed one of my files from `.js` to `.ts`

After that seems that templates cannot get imported nor `/` imports

    imports/ui/components/meteorSample.component.ts (10, 25): Cannot find module './meteorSample.html'.
    imports/ui/components/meteorSample.component.ts (12, 25): Cannot find module '/package.json'.

From `meteorSample.component.ts` file that looks like this

```ts
import { Component } from '@angular/core'
import templateUrl from './meteorSample.html'

import packageJson from '/package.json'

@Component({
  selector: 'meteor-sample',
  templateUrl: templateUrl.default
})
export class MeteorSampleComponent {
  constructor () {
    this.packageJson = packageJson
  }
}

```

**Comment by Hongbo-Miao** [comment]
It is related with Angular 2 instead of Angular2-Meteor.
http://stackoverflow.com/questions/36813780/using-relative-path-for-templateurl-in-angular2webpack

**Comment by trajano** [comment]
Actually that's also the case with Angular 1 also on Meteor, that's why it was good that @Urigo merged @kamilkisiela  changes for https://github.com/Urigo/angular-meteor/issues/1311 we just need the same thing to be done for Angular 2.

**Comment by kamilkisiela** [comment]
Very soon `urigo:static-templates` package will be able to import angular2 templates too, we're waiting for [this issue](meteor/meteor#7069) to be closed.

For now, we're using `html-minifier@0.8.0`, those `[] () *ngIf etc` attributes are being supported by newer version of this node module.

**Comment by barbatus** [comment]
Guys, why do you think `import templateUrl from './meteorSample.html'` is the right way to access 
`templateUrl`? I think proper use is to import HTML content instead in this way, in case you want component template to be delivered to the client along with the component itself, i.e.,

```ts
import template from './meteorSample.html'

@Component({
   template: template
})
```

**Comment by trajano** [comment]
From the comment by @Urigo regarding which one is better, the choice was to use the template content rather than a URL.

So...

    import template from './meteorSample.html'
    @Component({
       template                 // note property short cut
    })

should be the approach

**Comment by Hongbo-Miao** [comment]
@trajano this is normal way to use:

    @Component({
      selector: 'app',
      templateUrl: 'client/app.html'
    })

or 

    @Component({
      selector: 'app',
      template: `

      `
    })

**Comment by Urigo** [comment]
@barbatus it's not the best approach, it's a change towards the best approach which you described best.

The best approach is to import the content and this is being done by a new static-html package - https://github.com/Urigo/meteor-static-templates
this package is not Angular specific and works for both Angular 1.x and Angular 2.0.

So once the issue @kamilkisiela mentioned will be resolved we will publish new versions of Socially 1.0 and 2.0 that uses this package instead of `angular-html-templates` and `angular2-html-templates`.

But this is also a breaking change so I didn't want to change those packages but add a middle ground for people to start importing templates without 
1. Breaking APIs
2. import the templates twice (which would happen if we keep current behaviour + importing the content)

That way people can move to the new package whenever they want.

Would love to hear more opinions before publishing it

**Comment by trajano** [comment]
Would it be added via `meteor add static-templates`? Just so it looks more official. (no offence @Urigo )

**Comment by trajano** [comment]
Also can you make it so the there's a named export of `template`?

**Comment by trajano** [comment]
Also if `import './foo.html` is too difficult to implement in TypeScript we can do the `require` approach

```
@Component({
  selector: 'app',
  templateUrl: require('./app.html')
})
```

**Comment by barbatus** [comment]
@Urigo Not sure what sense did you mean saying it's an API breakage for the current package. Angular2 package hasn't had mentioned functionality so far. If you meant it's for the transition from Angular 1 to Angular 2, then does it mean you want less changes as possible to Babel files? If yes, there might multiple issues with TypeScript anyways.
For example, TypeScript will always curse on construction like `import url from './template.html'`, unless we hack the compiler. As was mentioned by trajano above, proper way would using `@Component({ template: require(./template.html)})`, which means it will need changes to the current way people using it in Angular1 and with Babel.
But yeah having one package for both Angular1 and Angular2 would be good, we then just need to remove `angular2-html-templates` at all from here and forget about imported URLs in Angular2

**Comment by trajano** [comment]
BTW, I just tried to do the `require` approach to see if what we have can work.  This is what I ended up with
```
@Component({
  selector: 'second-meteor-sample',
  templateUrl: require('./secondMeteorSample.html').default
})
```
kind of weird that I still need to put in default at the end.

**Comment by hlehmann** [comment]
Angular release `angular2-template-compiler` on npm while beginning it's rc stage. This mimic the typescript compiler but interprets template, templateUrl, styles and styleUrls in order to integrate all of this in a optimised js file.

Once compiled we can use bootstrap from `@angular/platform-browser` and not `@angular/platform-browser-dynamic` so it's smaller and rendering are faster. 

Would it be better to use angular compiler ?

**Comment by kamilkisiela** [comment]
In my opinion, the best approach is to load html file as a string directly to component so [`urigo:static-templates`](https://github.com/Urigo/meteor-static-templates) suits here really well.

This way we load templates synchronously, instead of using paths and loading it asynchronously.

Webpack's [`html-loader`](https://github.com/webpack/html-loader/blob/master/index.js) works the same way `urigo:static-templates` does.

---

About `@angular/compiler-cli`. We could create an atmosphere package that registers it as a compiler plugin.

---

About `angular2-html-templates`.

We could change `exports.default` to `module.exports`. This way we:

could use a require function:

```js
@Component({
  selector: 'second-meteor-sample',
  templateUrl: require('./secondMeteorSample.html')
})
```

or an import statement:

```js
import * as templateUrl from './secondMeteorSample.html';
@Component({
  templateUrl,
  selector: 'second-meteor-sample'
})
```


PS: @trajano `urigo:static-templates` supports now html5 attributes so you can use it even today with ng2 templates.

**Comment by hlehmann** [comment]
Is it necessary to make the import ?
```
@Component({
  moduleId: module.id, // /path/to/the/current/file
  templateUrl: './secondMeteorSample.html',
  selector: 'second-meteor-sample'
})
```

**Comment by kamilkisiela** [comment]
I think it's not.

Right now `angular2-html-templates` loads html files into assets, even if you don't import them. The `import` statement is only necessary if you want to receive absolute path of a template.

**Comment by Urigo** [comment]
@barbatus I agree that we need to bring the content and we are doing that here but I don't understand why using the `require` syntax is the right way of doing that.
I prefer the `import` syntax because it's in the standard.

So I want to understand first why `require` is better and if it's not, what we should do with Typescript to make it not complain about that

**Comment by trajano** [comment]
I don't think `require` is better, but typescript has no notion of `import` of HTML content, then again neither does `require`.  However, I think that `require` would be less work because the functionality should be part of Meteor.

**Comment by barbatus** [comment]
@Urigo The point is that template modules are being added virtually using Meteor API (i.e., `file.addJavaScript`), so TS compiler has no chance to know what has been added since there is no a real file behind that module.
Only solution I see currently is to keep track of all created JavaScript ES6 modules in some selected packages (like html compiler etc), and verify existence of each module that has not been found by the TS compiler, and then exclude error message from the produced diagnostics. As you can see it's not very much elegant.

From other side, when using `require` we'll completely reply on Meteor itself. So it'll curse if any imported module doesn't actually exist (real or virtual).

**Comment by trajano** [comment]
@barbatus when using `require` do you get this?

    Cannot find name 'require'.

I was thinking it can be resolved by http://stackoverflow.com/a/35961176/242042 but it does not appear to work.  However, the application still runs correctly from what I can tell.

**Comment by barbatus** [comment]
@trajano I would use NodeJS typings instead, anyways require typings seem should work too

**Comment by trajano** [comment]
>  I would use NodeJS typings instead,

How do I do that?

**Comment by barbatus** [comment]
BTW typescript@2.0 will allow to declare wildcard modules according to this issue https://github.com/Microsoft/TypeScript/issues/6615, so one can avoid warning when importing from .html (or any other) files with `declare module '*.html'`.

**Comment by barbatus** [comment]
With next versions of angular2-compiler `import content from './foo.html'` is only possible, check out https://github.com/Urigo/angular2-meteor#static-resources. Closing
