### ISSUE TITLE
Issues integrating ionic2.

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular2-meteor#319]
Having some css issues along with nav.present issue not working in iOS browser and webview. Check driftyco/ionic#7163 for details.

**Comment by kokokenada** [comment]
I'm having a lot of CSS problems with Ionic and Meteor too. On some views, when I use ion-content, it has the effect of hiding the contents.  Lots of problems around navigation (headers show up at bottom, new pushed Control does not get displayed - but that might because I'm not using ion-content as the docs show.)  Some problems on Android, but worse on iOS, e.g. black backgrounds and ion-list-headers show previous screen behind controls (iOS only). I doubt your problem has to do with the code specifically in this repository. (I'm using Meteor and Ionic, but not the angular2-meteor library at the moment.)  I'm suspicious of some sort of CSS conflict.  I'm still on Angular rc1 and plan to attack the problem after I do an upgrade.  By any chance, are you using Dragula?

**Comment by vacarsu** [comment]
No, not using Dragula. Honestly I don't have too many issues with ionic and meteor, just these couple of css issues and nav.present in iOS. Would really like too find out what I need to do to get it running well though. in the issues linked in the original post I have a repository where you can check out the issues.

**Comment by vacarsu** [comment]
Looks like I found a way to fix the css issues. first create a project with the Ionic CLI, change you variables in the ```app.variables.scss``` file, in the CLI type ```ionic serve``` which will build the css file in ```www/build/css``` copy this file over to the public folder in your meteor project. in your index file add the following to your head.

``` html
<link ios-href="css/app.ios.css" rel="stylesheet">
<link md-href="css/app.md.css" rel="stylesheet">
<link wp-href="css/app.wp.css" rel="stylesheet">
```
