### ISSUE TITLE
Question : Can't manage to import npm packages

### ISSUE THREAD

**Issue by eric-burel** [Urigo/angular2-meteor#347]
Hi,
I am having a lot of trouble loading npm packages from 3rd party libraries on the client side.
It does not seem to be an issue with Meteor itself, which usually manage to import packages (though it sometimes give me hard times), but with the interaction between Typescript/Angular/Meteor.

I saw thousands of Stack Overflow questions on the subject, each time too specific or solving the problem with a hack... Import works fine on well designed package, but most of the time developpers build there export for 'classical' use, not for Meteor.

Could you please provide an example of import that works at least on client side, for example for `plotly.js`, `d3` or `crossfilter2` ? That would help begginners a lot, and I'd like to improve the tutorial or the doc with some examples.

Edit :  to be precise, for the moment, I manually drop the minified js file of the library in the `client/compatibility` folder, and add a `declare var theObjectCreatedByMyPackage:any` (for example `declare var crossfilter : any` or `declare var Plotly : any`) so that the typescript compiler is happy

**Comment by Hongbo-Miao** [comment]
Hi @eric-burel, take d3 for example, you can search by using `typings search d3`.
There is a source showing `NPM`, so you can install by using `typings install d3 --save`.

If the source only has `dt`, you need install by `typings install dt~XXX --save`.

When you install, if you meet

> Attempted to compile "XXX" as an external module, but it looks like a global module. You'll need to enable the global option to continue.

You need add `--global`, like `typings install dt~XXX --global --save`

**Comment by eric-burel** [comment]
Thanks for this precision, I did not now about typings. Does the fact that I lacked a typings package can explain a failure when importing ? However, `import faker from 'faker'` still won't work after the typings package install.
Importing npm modules always works with a "vanilla" Meteor, so I guess the issue is related to typescript, or even to Meteor.

Can you please try to import faker in a file located in the `imports` folder in a small angular-meteor project for example ? That could help me to find out if the mistake is in my own code or not...

**Comment by barbatus** [comment]
The reason that you need to do `import * as faker from 'faker'` due to the fact that the faker doesn't export anything by default. Or in other words, `import foo from 'foo'` only works in TypeScript only if there is `modules.default = ...` inside that NPM.

On the your another points. I don't agree that using Meteor in that case differs from the "classical use". Meteor works with NPM now, so everything that matters stay the same. 
We presume that you understand the concept of the TypeScript definition files, if not you can read about them on Internet or in our [tutorial](http://www.angular-meteor.com/tutorials/socially/angular2/folder-structure)
At the same time, we provide some initial information (including README in this package) on the typings management and about the tooling we recommend to use: here https://github.com/Urigo/angular2-meteor#typings, here https://github.com/barbatus/typescript#typings and here https://github.com/meteor-typings/meteor.
I believe most people find it enough to begin with.
