### ISSUE TITLE
SCSS Import not working

### ISSUE THREAD

**Issue by Kamshak** [Urigo/angular2-meteor#393]
When using 

```
import style from './home.component.scss';
@Component({
	selector: 'home',
	template,
	styles: [style]
})
export class HomeComponent implements OnInit {
	constructor() { }
}
```
The following error occurs:
```
Uncaught Error: Expected 'styles' to be an array of strings.
```

**Comment by derek-fong** [comment]
@Kamshak Are your `*.component.ts` and `*.component.scss` files saved under the `imports` folder? 

I came across with similar issue #324 and I noticed it only works when you place your  `*.component.ts` and `*.component.scss` under `imports/client/<some-feature>` folder similar to the 
[TODO Demo](https://github.com/Urigo/angular2-meteor/tree/master/examples/todos-meteor-1.3/imports/components).

**Comment by PseudoPsycho** [comment]
@derek-fong I don't think this is necessary anymore.
@Kamshak You could try to import ./home.component.css instead of css (or .scss.css or something like that) as it might depend your setup. I think the file gets converted before the module bundler imports it, so you probably want to include the processed .css file.

**Comment by derek-fong** [comment]
@PseudoPsycho I have just tested it again by creating a "demo" app and confirmed any `*.scss` imports will fail with the error that @Kamshak mentioned if the `*.scss` file is placed under `client/imports`. However it works fine if `*.scss` is placed under `imports/client`. 

I have created a [repo](https://github.com/derek-fong/socially.git) to replicate the behaviour and this can be confirmed by switching [these two line of codes](https://github.com/derek-fong/socially/blob/master/client/imports/demo/demo.component.ts#L7-L8). 

Not sure if there are any additional setup that I have missed out or the [css-complier docs](https://github.com/Urigo/angular2-meteor/blob/master/atmosphere-packages/css-compiler/README.md) did not mention?

**Comment by Kamshak** [comment]
I see, thanks! It's a bit strange that the default seed project at https://github.com/bsliran/angular2-meteor-base/tree/master/client (meteor create --example angular2-boilerplate) does it the client/imports way.

**Comment by derek-fong** [comment]
@Kamshak that's because `angular2-meteor-base` [imports components' scss in `app.component.scss`](https://github.com/bsliran/angular2-meteor-base/blob/master/client/app.component.scss#L5). 

If my understanding is correct: Styling rules import in `app.component.scss` will be available application-wide while `import style from './foo.component.scss'` in your component will be component-specific (Please correct me if I am wrong :)) 

I mean either way it will work - It really depends on how you manage your project. 

That being said, personally I prefer the `import style from './foo.component.scss'` approach as it encourages modularising codes. 

I have created a [repo](https://github.com/derek-fong/angular2-meteor-boilerplate.git) which is a simple demo of my recent angular2-meteor project. 

The project structure has been organise in a way based on the ideas from [Meteor's Application Structure Guide](https://guide.meteor.com/structure.html#javascript-structure), [Angular 2 Style Guide](https://angular.io/styleguide) and [angular2-meteor-base](https://github.com/bsliran/angular2-meteor-base) - Not sure if this is the `correct` way to organise the app but at least it works for me :)

Feel free to checkout the repo and let me know if there is any problem :)

**Comment by Kamshak** [comment]
Cheers, thanks for your efforts!

**Comment by BadOPCode** [comment]
Kind of late to this party... but I just ran into this one myself.  Reading through the boilerplate code I found the problem.
When your using Angular-Meteor the *.component.scss that is placed inside this component directory, it needs to start the root object as ```:host``` referring to the component container itself.  Which makes sense to do this because the selector name is being set in *.component.ts.   Keeps you from having to make a bunch of code changes in multiple files just to change the selector.
But like yourself, I was trying to set it to the name of the selector itself, in your example starting the root object as ```home { ... }```.
So take out home and make your home.component.scss like...
```
:host {
    color:black;
    ....
}
```
