### ISSUE TITLE
Valid tutorial

### ISSUE THREAD

**Issue by gooor** [Urigo/angular2-meteor#407]
Is there any valid tutorial or any working example of how to begin? I'm asking because  https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping just doesn't work. And angular2-meteor-base show completely different and also does not work at all.

**Comment by juliocesar12** [comment]
I have the same problem, I don't know if it is possible to update the tutorial :pray:

**Comment by slippyC** [comment]
They have changed things quite a bit.  A lot of the stuff use to be built into meteor itself, through it's package system.  I'm having to do some catching up myself, because I'm starting to have issues with the way they use to have things setup.  I wish they would have let people know they were moving straight to npm instead of depending on meteor's package manager though.  I'm sure there was a good reason for it, but kind of frustrating.

I think the problem you are having is different tutorials seem to be coming from different angles of how you may want to start.  One assumes you are starting with an Angular2 base, another one or two seems to be starting from a meteor base and building from there.

If you are going to work from the one over on the angular-meteor site, I wouldn't mess with the main.ts.  Just leave it the way it is except for changing where the `import { AppModule } from './imports/app'` is.
That is where your app.ts or app.component.ts files needs to be referenced from.  

I have not gone through the whole thing again, but this should get you started and keeping you from pulling the rest of your hair out.

**Comment by slippyC** [comment]
Yep, angular-meteor website tutorial is all messed up at this point in time.  I have tried forcing different versions of angular2-meteor package too.

I had started running into problems with the old way they were doing things.  A lot of the package stuff was built into meteor's package system.  They had migrated away from that to npm based.  So they weren't updating packages for the meteor package system.  Which meant bugs were not getting fixed.  

If you are using 0.7.0, you are going to get bootloader issues.  If  you try 0.6.0 you are going to get a lot of other issues.  I'm not knowledgable enough of the inner-workings to fix it or I would suggest fixes(improve doc).  There is also a part in the doc that says there is no `<head>` or `<html>` tag on the very first page(section 0.3).  Yet right above there is `<head>` tag.  This is because this was left over from the old tutorial.  I could care less about that, but a working setup would be nice.

**Comment by slippyC** [comment]
Alright, I have figured out a way for you guys to test if you want.

`
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import {AppComponent} from './imports/app/app'; //<=======This is points to your first component

const platform = platformBrowserDynamic();

@NgModule({
    imports: [
        BrowserModule
    ],
    declarations: [
        AppComponent
    ],
    bootstrap: [
        AppComponent
    ]
})
export class AppModule {}


platform.bootstrapModule(AppModule);
`

**Comment by kamilkisiela** [comment]
Tutorial has been updated. I recommend you to use a new thing called [`meteor-rxjs`](https://www.npmjs.com/package/meteor-rxjs), Meteor API combined with RxJS.

**Comment by Urigo** [comment]
sorry everyone it took long, it was very hard keeping up with the Angular releases.
Now we are finally updated, stable and final

**Comment by gooor** [comment]
@Urigo You're my hero 👍
