### ISSUE TITLE
Info about TypeScript 2 and paths usage

### ISSUE THREAD

**Issue by emilianosantucci** [Urigo/angular2-meteor#420]
With TypeScript 2, `baseUrl` and `paths` parameters are introduced.
With those, I was thinking to refactoring the `import`'s of relative paths in more readably forms.

For example, I want change from:
`import ../../../../foo.module;`
to:
`import modules/foo/foo.module:`

So, I tried to proper reconfigure my `tsconfig.json` with that:
```json
    "baseUrl": ".",
    "paths": {
      "app/*": ["client/imports/app/*"],
      "utils/*": ["client/imports/shared/utils/*"],
      "pages/*": ["client/imports/+*"],
      "client-shared/*": ["client/imports/shared/*"],
      "models/*": ["shared/models/*"],
      "collections/*": ["shared/collections/*"],
      "mocks/*": ["server/mocks/*"],
      "client/*": ["client/*"],
      "server/*": ["server/*"],
      "*": ["node_modules/*"]
    }
```
Before launch `meteor`, I've tried with `tsc -p . --outDir example --traceResolution` and it works fine.
With meteor, however, the sounds change.
Surfing into created bundle, I see that the "virtual" path isn't "translated" and it can't reach modules.

So, I have two questions for you:
 1. My usage of `paths` to do this is correct or I'm wrong?
 2. If answer at question 1 is **yes**, how will drive meteor (and ts compiler) to map the paths correctly?

Thanks

**Comment by barbatus** [comment]
Please read this issue https://github.com/barbatus/typescript/issues/30.
It doesn't work today because TypeScript doesn't  transform imports according to as defined in`paths` option in the transpiled code, you require to configure your bundler (e.g. Webpack) to use same configuration. Meteor at the same time  sticks strictly to Node.js resolution strategy and no way to configure it. Unfortunately, it won't work until I'll implement paths mangling, which might take some time. I recommend to use rooted paths, i.e., `app/foo/foo.ts` -> `/client/imports/app/foo.ts`.

**Comment by emilianosantucci** [comment]
Ok, currently my paths is all rooted. Thanks @barbatus, I hope help you to reach this goal ;).

**Comment by emilianosantucci** [comment]
PS: @barbatus have you that implementation in your roadmap?
