### ISSUE TITLE
angular2-compilers stylesheets problem

### ISSUE THREAD

**Issue by omararturo** [Urigo/angular2-meteor#429]
Hi,
First of all, thank all those who in some way contribute to the development of angular2-compilers.

I'm developing in angular2 with meteor and want to share everything I can with the community. Far from criticizing, I think we share mistakes is a way to contribute to this development.

I detected an error in the version angular2-compilers@0.6.4.

I present an example that will allow us to understand the error:

./client/imports/user/user-edit.component.ts

```
import { Component, OnInit } from '@angular/core';
import { MeteorComponent } from 'angular2-meteor';

import template from './user-edit.component.html';
import style from './user-edit.component.scss';

@Component({
    selector: 'user-edit',
    template,
    styles: [style]
})
export class UserEditComponent extends MeteorComponent implements OnInit {    

    constructor(        
    ) {
        super();
    }

    ngOnInit() {
    }
}
```

./client/imports/user/user-edit.component.html
This is the tabs component from @angular/material

```
<md-tab-group selectedIndex="0">
    <md-tab>
        <template md-tab-label>
            <md-icon class="s36" title="User Create">looks_one</md-icon>
            USER CREATE
        </template>
        <template md-tab-content>
            // ...
        </template>
    </md-tab>
</md-tab-group>
```

./client/imports/user/user-edit.component.scss

```
md-tab-group div.md-tab-label {
  min-width: 25%  !important;
  max-width: 25%  !important;
}

md-tab-group div.md-tab-header md-ink-bar {
  min-width: 25%  !important;
  max-width: 25%  !important;
}
```

I'm you trying to change the default size of the "md-tab-header" (generated in "template md-tab-label") in the component tabs in angular2 material is not shown in the template because this code is generated from the component tabs. Only I have access to the elements found in the template and not to those generated.

It only works if for example create a file in the root of the "client" folder example:
./client/fix-material.scss

```
md-tab-group div.md-tab-label {
  min-width: 25%  !important;
  max-width: 25%  !important;
}

md-tab-group div.md-tab-header md-ink-bar {
  min-width: 25%  !important;
  max-width: 25%  !important;
}
```

I think this must be solved for each component control the content it contains.

**Comment by dotansimha** [comment]
@omararturo please refer to [Angular 2 Component Styles documentation](https://angular.io/docs/ts/latest/guide/component-styles.html). 
I don't think it's an issue with `angular2-compilers`, because Angular 2 encapsulates each Component's styles by it self, without any chance to override other Component's styles. 
It means that every Component has it's own style - and it can effect only the elements that it creates (NOT the Components it uses) - which means that every Angular 2 Component that uses Angular2-Material Component's, can decide only the parent element style (for example `md-tab-group` which is the parent).

More in depth, Angular 2 changes every CSS stylesheet and append unique identifiers for each style created, and then add the same unique identifier to the matching elements.
Which means that each Component will have it's own identifier, and your `md-tab-group` will get the styles from the stylesheet of your Component, but it's child elements (such as `md-tab`) can get it's styles only from the `md-tab-group` stylesheet.

There are workaround, such as adding the stylesheet outside the Component's context (in the global styles) and then risk overriding other Component's styles. 

But you can also use the Angular 2 special selectors, such as `/deep/` to override the style of you child Components, and then effect the entire Component's tree, instead of only the first level.

Usage example:

``` css
md-tab-group /deep/ div.md-tab-label {
  min-width: 25%  !important;
  max-width: 25%  !important;
}
```

You can read more in the documentation page I mentioned.

Good luck!
