### ISSUE TITLE
Import from relative path 

### ISSUE THREAD

**Issue by Matanlb** [Urigo/angular2-meteor#47]
Hi,

I've been trying incorporate Angular 2 in our system which is currently using blaze, step by step.

Doing the [tutorial](http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping) for Angular 2 And I've noticed that while in the tutorial, and in another "pure" Angular2 small prototype, the **_import {Something} from './some/relative/path'_** does not work the same way in when the system contains both  Meteor-Angular2 and Blaze.

Instead, the path given in the statement must be of an *'absolute'* path, **_/project/root/to/file_** (i.e the initial / stands for the project root, not the system root).

Any idea why this difference exist? is can be very confusing for a lot of "Tutorial Graduates".

**Comment by juanpujol** [comment]
For me the import works as relative and absolute.

You need to start the path from `/client`. So if you go absolute it will be something like:

`import {UsersComponent} from 'client/components/users/users.component';`

And if you want to do a relative import to let's say `client/components/subscribers/subscribers.component.ts` the you do it like this:

`import {UsersComponent} from '../../components/users/users.component';`

Hope it helps.

**Comment by barbatus** [comment]
Does it work if Meteor-Angular2 used without Blaze?
Also absolute paths not necessarily should start from "/", as said in the prev comment.
if you can refer to your repo to with that issue, it would be awesome.

**Comment by ujinv** [comment]
I have the same issue. More info: on the client side I can import everything using relative paths as my IDE helps me (Atom). But when I try to do the same thing in server-side code I receive build errors with wrong paths:
![2016-01-15_23-15-49](https://cloud.githubusercontent.com/assets/377725/12364201/555e9422-bbde-11e5-9bdb-de040a061b62.png)

The wrong thing is that relative path "./inittags" is resolved as 'c:\devel\inittags' instead of 'c:\devel\!scada\server\inittags' if I set import path to 'server/inittags' then build is OK, but IDE shows error "cannot find module server/inittags"

**Comment by barbatus** [comment]
@ujinv you can remove now `/// <reference ...` sugar. It's preferable now to use tsconfig instead, see Tutorial's Step 7 http://www.angular-meteor.com/tutorials/socially/angular2/folder-structure.
You can find there as well how to configure Atom right. 
if you face same issue after proper tsconfig.json setup, then I'll need a repo to figure what's the problem; same paths work find for the demo apps.

**Comment by ujinv** [comment]
Thanks for pointing to the updated tutorial! I did walk through it, but it was quite a while ago.
It works fine now. BTW #69 is solved with proper tsconfig.json too.

**Comment by barbatus** [comment]
Assuming it closed since din't see how Blaze can prevent importing from relative paths.
