### ISSUE TITLE
support ngUpgrade and ngForward

### ISSUE THREAD

**Issue by jamalx31** [Urigo/angular2-meteor#50]
is that coming soon ?

**Comment by barbatus** [comment]
There already exists a solution of the similar kind that includes Meteor support https://github.com/pbastowski/angular2-now. Did you try it?

**Comment by jamalx31** [comment]
@barbatus not really.
Is it so hard to add ngUpgrade to angular2-meteor package or make new package to support it.
I tried this:
add angular 1 package manual and remove angular-templates from it's dependency to resolve the conflict with angular2-meteor. I tried to add ngUpgrade but I couldn't bootstrap my app with it.
I guess SystemJs had a problem with what I did.
What do you think ?

**Comment by barbatus** [comment]
No, I've tried it as well. I think we need first to figure out is any reason to use ngUpgrade over Angular2Now. @pbastowski Hi, Paul. What do you think? Thanks for the answer in advance.

**Comment by pbastowski** [comment]
I haven't used ngUpgrade myself either. 

However, ngUpgrade is a different beast to angular2-now and ngForward. It is a bridging library that allows Angular1 and Angular2 to run side by side in the same web app and share common resources, for example directives/components. So, let's hear that again, both Angular1 and Angular2 libraries, plus the ngUpgrade library, will be loaded and running at the same time in your browser. Personally, I don't plan on using this approach in any of my projects due to the extra complexity it brings.

So, it's not really a matter of using ngUpgrade or angular2-now / ngForward.

angular2-now (my library) makes it possible to write code that looks and feels like Angular2 components and makes coding in Angular1 with ui-router very simple, while still using Angular1. So, no actual Angular2 is required and no ngUpgrade needed.

ngForward has nothing to do with ngUpgrade. It is a library very much like my own angular2-now, but it provides even more support for Angular2 features in your Angular1 apps. However, that comes at a cost of increased library code size and complexity. If you need those extra features or want your code to look even closer to actual Angular2 code then ngForward could be the way to go.

I am using angular2-now in my production apps, because I know my library very well, have used it in production apps for several months already and am satisfied with the features it provides to my Angular1 apps.

So, I am not currently planning on creating an ngForward or ngUpgrade package for Meteor. But that may change in the future :)

**Comment by barbatus** [comment]
@pbastowski Thanks for the great answer. @jamalx31 Having Angular 1 and Angular 2 in one project sounds an overkill to me too. So it's not of a high priority, taking into account it doesn't seem to be a simple task as well. Will see what we can do with it after Meteor 1.3 release.

**Comment by sebakerckhof** [comment]
@barbatus I do think it's very interesting/important for angular 1 projects that want to switch to angular 2, but can't do it all in one big bang (because their own codebase is too large, or they rely on third-party components without angular 2 alternative).

**Comment by Urigo** [comment]
Here is a tutorial how to do that - http://www.angular-meteor.com/tutorials/socially/angular1/migration-to-angular2
