### ISSUE TITLE
timeline

### ISSUE THREAD

**Issue by nor-bu** [Urigo/angular2-meteor#58]
hi,

many thanks for the great work with angular2-meteor and meteor.
The roadmap looks great!

But how is the timeline for 1.0?

thanks and happy new year

**Comment by barbatus** [comment]
It depends how soon you start contributing.

**Comment by barbatus** [comment]
As you understand, open-source projects usually don't have timelines since they are developed by a community. You can check, though, from time to time this roadmap [here](https://trello.com/b/kSa6JNCk/angular2-tutorial), where status are expected to be updated periodically with new features onboard.
