### ISSUE TITLE
Better way to count Items And Graphs

### ISSUE THREAD

**Issue by franzsilva** [Urigo/angular2-meteor#59]
Hey guys. 

First of all i just wanted to say that im a Nº1 Fan of angular-meteor. And the work you guys are doing is absolutly awesome. And a special Congrats to Uri Who started all of this.

That been said. I have an inquiry about counting large datasets. Currently im starting to learn meteor well and also Angular2, we are building a project which will show realtime Graphs. And i had a question about the count module you use on the tutorial, I was investingating a bit about it and on the github page they state that the library shouldnt be used for data larger than 100 records. Im guesing because of performance. If i wanted to collect counted data from a mongo query on the server and have it sent to the client reactively, what would you consider to be a best practice to acomplish this. And how would you go about implementing charts on angular2-meteor apps.

PS. Ill probably start blogging about Angular2-meteor and Meteor on my newly created site franzsilva.com. Dont have any blog posts yet. but Angular2-meteor and Meteor will be my first. 

Thank you

Regards,
Franz

**Comment by Urigo** [comment]
Hi @franzsilva this is a really good question but it's not Angular specific because your question is about publications.
I would post this question on Stack overflow with the `meteor` tag and also on the [Meteor forums](https://forums.meteor.com/).
I'm closing now but please add a comment with a link to your questions there.
thank you
