### ISSUE TITLE
CollectionFS working?

### ISSUE THREAD

**Issue by Jonarod** [Urigo/angular2-meteor#65]
THANK YOU for the GREAT documentation made so far on using Angular-meteor and Angular2-meteor.

Steps 16 and up have not been written yet for angular 2.0 tutorial and I can seem to integrate CollectionFS or understand how I can do it in angular 2.0 (Step 20).

Is CollectionFS (and other unwritten steps like ionic, gMaps...) not implemented in angular2-meteor yet?
Where can I find bare documentation/example on it ?

Thank you !!

**Comment by mehdibalouchi** [comment]
I was trying to work with CollectionFS and it seems that it is very hard to use that in angular2-meteor. the reason is helpers that do lots of things and are not available in angular2-meteor.
I wanted to ask if any temporary solution exists for now.
I am developing some kind of social network and CollectionFS would be very helpful.
thanks a lot

**Comment by barbatus** [comment]
Step about CollectionFS is not written yet, hence, CollectionFS is not tested with Angular2-Meteor.
Since we are moving step by step in the tutorial, and there are like 3 steps left before the one with CollectionFS, I expect it to be done within next 2-3 weeks or so. This's what I can say.

**Comment by janibekm** [comment]
hello! I was trying to use gridFS or collectionFS to angular2. So angular-meteor com step 20 is not written yet, when we can use collectionFS, it is possible now use angular2. If it is possible, can you explain how to use it for some example. Thank you!
